--🔹 1. Insert Data into stores
INSERT INTO stores (store_id, store_name, city, country)
VALUES
(1, 'Apple Store New York', 'New York', 'USA'),
(2, 'Apple Store London', 'London', 'UK'),
(3, 'Apple Store Dubai', 'Dubai', 'UAE'),
(4, 'Apple Store Tokyo', 'Tokyo', 'Japan'),
(5, 'Apple Store Sydney', 'Sydney', 'Australia'),
(6, 'Apple Store Paris', 'Paris', 'France'),
(7, 'Apple Store Berlin', 'Berlin', 'Germany'),
(8, 'Apple Store Toronto', 'Toronto', 'Canada'),
(9, 'Apple Store Singapore', 'Singapore', 'Singapore'),
(10, 'Apple Store Mumbai', 'Mumbai', 'India'),
(11, 'Apple Store Seoul', 'Seoul', 'South Korea'),
(12, 'Apple Store Barcelona', 'Barcelona', 'Spain'),
(13, 'Apple Store Rome', 'Rome', 'Italy'),
(14, 'Apple Store São Paulo', 'São Paulo', 'Brazil'),
(15, 'Apple Store Johannesburg', 'Johannesburg', 'South Africa'),
(16, 'Apple Store Zurich', 'Zurich', 'Switzerland'),
(17, 'Apple Store Amsterdam', 'Amsterdam', 'Netherlands'),
(18, 'Apple Store Istanbul', 'Istanbul', 'Turkey'),
(19, 'Apple Store Bangkok', 'Bangkok', 'Thailand'),
(20, 'Apple Store Kuala Lumpur', 'Kuala Lumpur', 'Malaysia'),
(21, 'Apple Store Vienna', 'Vienna', 'Austria'),
(22, 'Apple Store Brussels', 'Brussels', 'Belgium'),
(23, 'Apple Store Warsaw', 'Warsaw', 'Poland'),
(24, 'Apple Store Prague', 'Prague', 'Czech Republic'),
(25, 'Apple Store Athens', 'Athens', 'Greece'),
(26, 'Apple Store Helsinki', 'Helsinki', 'Finland'),
(27, 'Apple Store Oslo', 'Oslo', 'Norway'),
(28, 'Apple Store Copenhagen', 'Copenhagen', 'Denmark'),
(29, 'Apple Store Stockholm', 'Stockholm', 'Sweden'),
(30, 'Apple Store Budapest', 'Budapest', 'Hungary'),
(31, 'Apple Store Dublin', 'Dublin', 'Ireland'),
(32, 'Apple Store Mexico City', 'Mexico City', 'Mexico'),
(33, 'Apple Store Buenos Aires', 'Buenos Aires', 'Argentina'),
(34, 'Apple Store Santiago', 'Santiago', 'Chile'),
(35, 'Apple Store Lima', 'Lima', 'Peru'),
(36, 'Apple Store Bogota', 'Bogota', 'Colombia'),
(37, 'Apple Store Caracas', 'Caracas', 'Venezuela'),
(38, 'Apple Store Panama City', 'Panama City', 'Panama'),
(39, 'Apple Store San Juan', 'San Juan', 'Puerto Rico'),
(40, 'Apple Store Doha', 'Doha', 'Qatar'),
(41, 'Apple Store Riyadh', 'Riyadh', 'Saudi Arabia'),
(42, 'Apple Store Kuwait City', 'Kuwait City', 'Kuwait'),
(43, 'Apple Store Muscat', 'Muscat', 'Oman'),
(44, 'Apple Store Manama', 'Manama', 'Bahrain'),
(45, 'Apple Store Tehran', 'Tehran', 'Iran'),
(46, 'Apple Store Baghdad', 'Baghdad', 'Iraq'),
(47, 'Apple Store Cairo', 'Cairo', 'Egypt'),
(48, 'Apple Store Nairobi', 'Nairobi', 'Kenya'),
(49, 'Apple Store Casablanca', 'Casablanca', 'Morocco'),
(50, 'Apple Store Lagos', 'Lagos', 'Nigeria'),
(51, 'Apple Store Accra', 'Accra', 'Ghana'),
(52, 'Apple Store Algiers', 'Algiers', 'Algeria'),
(53, 'Apple Store Kampala', 'Kampala', 'Uganda'),
(54, 'Apple Store Rabat', 'Rabat', 'Morocco'),
(55, 'Apple Store Lusaka', 'Lusaka', 'Zambia'),
(56, 'Apple Store Harare', 'Harare', 'Zimbabwe'),
(57, 'Apple Store Dakar', 'Dakar', 'Senegal'),
(58, 'Apple Store Tunis', 'Tunis', 'Tunisia'),
(59, 'Apple Store Beirut', 'Beirut', 'Lebanon'),
(60, 'Apple Store Tbilisi', 'Tbilisi', 'Georgia'),
(61, 'Apple Store Yerevan', 'Yerevan', 'Armenia'),
(62, 'Apple Store Baku', 'Baku', 'Azerbaijan'),
(63, 'Apple Store Hanoi', 'Hanoi', 'Vietnam'),
(64, 'Apple Store Manila', 'Manila', 'Philippines'),
(65, 'Apple Store Jakarta', 'Jakarta', 'Indonesia'),
(66, 'Apple Store Ho Chi Minh City', 'Ho Chi Minh City', 'Vietnam'),
(67, 'Apple Store Taipei', 'Taipei', 'Taiwan'),
(68, 'Apple Store Islamabad', 'Islamabad', 'Pakistan'),
(69, 'Apple Store Dhaka', 'Dhaka', 'Bangladesh'),
(70, 'Apple Store Colombo', 'Colombo', 'Sri Lanka'),
(71, 'Apple Store Kathmandu', 'Kathmandu', 'Nepal'),
(72, 'Apple Store Thimphu', 'Thimphu', 'Bhutan'),
(73, 'Apple Store Ulaanbaatar', 'Ulaanbaatar', 'Mongolia'),
(74, 'Apple Store Ashgabat', 'Ashgabat', 'Turkmenistan'),
(75, 'Apple Store Tashkent', 'Tashkent', 'Uzbekistan'),
(76, 'Apple Store Bishkek', 'Bishkek', 'Kyrgyzstan'),
(77, 'Apple Store Dushanbe', 'Dushanbe', 'Tajikistan'),
(78, 'Apple Store Nuuk', 'Nuuk', 'Greenland'),
(79, 'Apple Store Reykjavik', 'Reykjavik', 'Iceland'),
(80, 'Apple Store Tallinn', 'Tallinn', 'Estonia'),
(81, 'Apple Store Riga', 'Riga', 'Latvia'),
(82, 'Apple Store Vilnius', 'Vilnius', 'Lithuania'),
(83, 'Apple Store Luxembourg City', 'Luxembourg City', 'Luxembourg'),
(84, 'Apple Store Monaco', 'Monaco', 'Monaco'),
(85, 'Apple Store Andorra la Vella', 'Andorra la Vella', 'Andorra'),
(86, 'Apple Store Valletta', 'Valletta', 'Malta'),
(87, 'Apple Store Ljubljana', 'Ljubljana', 'Slovenia'),
(88, 'Apple Store Zagreb', 'Zagreb', 'Croatia'),
(89, 'Apple Store Belgrade', 'Belgrade', 'Serbia'),
(90, 'Apple Store Sarajevo', 'Sarajevo', 'Bosnia and Herzegovina'),
(91, 'Apple Store Skopje', 'Skopje', 'North Macedonia'),
(92, 'Apple Store Podgorica', 'Podgorica', 'Montenegro'),
(93, 'Apple Store Chisinau', 'Chisinau', 'Moldova'),
(94, 'Apple Store Havana', 'Havana', 'Cuba'),
(95, 'Apple Store Kingston', 'Kingston', 'Jamaica'),
(96, 'Apple Store Port of Spain', 'Port of Spain', 'Trinidad and Tobago'),
(97, 'Apple Store Bridgetown', 'Bridgetown', 'Barbados'),
(98, 'Apple Store Nassau', 'Nassau', 'Bahamas'),
(99, 'Apple Store Male', 'Male', 'Maldives'),
(100, 'Apple Store Suva', 'Suva', 'Fiji'),
(101, 'Apple Store Perth', 'Perth', 'Australia'),
(102, 'Apple Store Canberra', 'Canberra', 'Australia'),
(103, 'Apple Store Christchurch', 'Christchurch', 'New Zealand'),
(104, 'Apple Store Wellington', 'Wellington', 'New Zealand'),
(105, 'Apple Store Anchorage', 'Anchorage', 'USA'),
(106, 'Apple Store Honolulu', 'Honolulu', 'USA'),
(107, 'Apple Store Quebec City', 'Quebec City', 'Canada'),
(108, 'Apple Store Edmonton', 'Edmonton', 'Canada'),
(109, 'Apple Store Calgary', 'Calgary', 'Canada'),
(110, 'Apple Store Hamilton', 'Hamilton', 'New Zealand'),
(111, 'Apple Store Gold Coast', 'Gold Coast', 'Australia'),
(112, 'Apple Store Adelaide', 'Adelaide', 'Australia'),
(113, 'Apple Store Hobart', 'Hobart', 'Australia'),
(114, 'Apple Store Darwin', 'Darwin', 'Australia'),
(115, 'Apple Store Chandigarh', 'Chandigarh', 'India'),
(116, 'Apple Store Jaipur', 'Jaipur', 'India'),
(117, 'Apple Store Ahmedabad', 'Ahmedabad', 'India'),
(118, 'Apple Store Kochi', 'Kochi', 'India'),
(119, 'Apple Store Indore', 'Indore', 'India'),
(120, 'Apple Store Lucknow', 'Lucknow', 'India'),
(121, 'Apple Store Visakhapatnam', 'Visakhapatnam', 'India'),
(122, 'Apple Store Bhopal', 'Bhopal', 'India'),
(123, 'Apple Store Patna', 'Patna', 'India'),
(124, 'Apple Store Guwahati', 'Guwahati', 'India'),
(125, 'Apple Store Bhubaneswar', 'Bhubaneswar', 'India'),
(126, 'Apple Store Dehradun', 'Dehradun', 'India'),
(127, 'Apple Store Ranchi', 'Ranchi', 'India'),
(128, 'Apple Store Raipur', 'Raipur', 'India'),
(129, 'Apple Store Srinagar', 'Srinagar', 'India'),
(130, 'Apple Store Shimla', 'Shimla', 'India'),
(131, 'Apple Store Imphal', 'Imphal', 'India'),
(132, 'Apple Store Agartala', 'Agartala', 'India'),
(133, 'Apple Store Itanagar', 'Itanagar', 'India'),
(134, 'Apple Store Aizawl', 'Aizawl', 'India'),
(135, 'Apple Store Kohima', 'Kohima', 'India'),
(136, 'Apple Store Gangtok', 'Gangtok', 'India'),
(137, 'Apple Store Port Blair', 'Port Blair', 'India'),
(138, 'Apple Store Siliguri', 'Siliguri', 'India'),
(139, 'Apple Store Nagpur', 'Nagpur', 'India'),
(140, 'Apple Store Vadodara', 'Vadodara', 'India'),
(141, 'Apple Store Nashik', 'Nashik', 'India'),
(142, 'Apple Store Amritsar', 'Amritsar', 'India'),
(143, 'Apple Store Jodhpur', 'Jodhpur', 'India'),
(144, 'Apple Store Ludhiana', 'Ludhiana', 'India'),
(145, 'Apple Store Meerut', 'Meerut', 'India'),
(146, 'Apple Store Varanasi', 'Varanasi', 'India'),
(147, 'Apple Store Kanpur', 'Kanpur', 'India'),
(148, 'Apple Store Ghaziabad', 'Ghaziabad', 'India'),
(149, 'Apple Store Faridabad', 'Faridabad', 'India'),
(150, 'Apple Store Noida', 'Noida', 'India'),
(151, 'Apple Store Gurgaon', 'Gurgaon', 'India'),
(152, 'Apple Store Pune', 'Pune', 'India'),
(153, 'Apple Store Surat', 'Surat', 'India'),
(154, 'Apple Store Rajkot', 'Rajkot', 'India'),
(155, 'Apple Store Jabalpur', 'Jabalpur', 'India'),
(156, 'Apple Store Gwalior', 'Gwalior', 'India'),
(157, 'Apple Store Cuttack', 'Cuttack', 'India'),
(158, 'Apple Store Mangalore', 'Mangalore', 'India'),
(159, 'Apple Store Mysore', 'Mysore', 'India'),
(160, 'Apple Store Salem', 'Salem', 'India'),
(161, 'Apple Store Trichy', 'Trichy', 'India'),
(162, 'Apple Store Madurai', 'Madurai', 'India'),
(163, 'Apple Store Tirupati', 'Tirupati', 'India'),
(164, 'Apple Store Nellore', 'Nellore', 'India'),
(165, 'Apple Store Kurnool', 'Kurnool', 'India'),
(166, 'Apple Store Rajahmundry', 'Rajahmundry', 'India'),
(167, 'Apple Store Vijayawada', 'Vijayawada', 'India'),
(168, 'Apple Store Warangal', 'Warangal', 'India'),
(169, 'Apple Store Karimnagar', 'Karimnagar', 'India'),
(170, 'Apple Store Nizamabad', 'Nizamabad', 'India'),
(171, 'Apple Store Moradabad', 'Moradabad', 'India'),
(172, 'Apple Store Aligarh', 'Aligarh', 'India'),
(173, 'Apple Store Bareilly', 'Bareilly', 'India'),
(174, 'Apple Store Saharanpur', 'Saharanpur', 'India'),
(175, 'Apple Store Gorakhpur', 'Gorakhpur', 'India'),
(176, 'Apple Store Muzaffarpur', 'Muzaffarpur', 'India'),
(177, 'Apple Store Dhanbad', 'Dhanbad', 'India'),
(178, 'Apple Store Bokaro', 'Bokaro', 'India'),
(179, 'Apple Store Jamshedpur', 'Jamshedpur', 'India'),
(180, 'Apple Store Asansol', 'Asansol', 'India'),
(181, 'Apple Store Durgapur', 'Durgapur', 'India'),
(182, 'Apple Store Silchar', 'Silchar', 'India'),
(183, 'Apple Store Dibrugarh', 'Dibrugarh', 'India'),
(184, 'Apple Store Tezpur', 'Tezpur', 'India'),
(185, 'Apple Store Shillong', 'Shillong', 'India'),
(186, 'Apple Store Dimapur', 'Dimapur', 'India'),
(187, 'Apple Store Tura', 'Tura', 'India'),
(188, 'Apple Store Aalo', 'Aalo', 'India'),
(189, 'Apple Store Itarsi', 'Itarsi', 'India'),
(190, 'Apple Store Satna', 'Satna', 'India'),
(191, 'Apple Store Puri', 'Puri', 'India'),
(192, 'Apple Store Sambalpur', 'Sambalpur', 'India'),
(193, 'Apple Store Guntur', 'Guntur', 'India'),
(194, 'Apple Store Ongole', 'Ongole', 'India'),
(195, 'Apple Store Nanded', 'Nanded', 'India'),
(196, 'Apple Store Solapur', 'Solapur', 'India'),
(197, 'Apple Store Akola', 'Akola', 'India'),
(198, 'Apple Store Latur', 'Latur', 'India'),
(199, 'Apple Store Jalgaon', 'Jalgaon', 'India'),
(200, 'Apple Store Kolhapur', 'Kolhapur', 'India'),
(201, 'Apple Store Edinburgh', 'Edinburgh', 'UK'),
(202, 'Apple Store Birmingham', 'Birmingham', 'UK'),
(203, 'Apple Store Glasgow', 'Glasgow', 'UK'),
(204, 'Apple Store Cardiff', 'Cardiff', 'UK'),
(205, 'Apple Store Oslo Central', 'Oslo', 'Norway'),
(206, 'Apple Store Bergen', 'Bergen', 'Norway'),
(207, 'Apple Store Hamburg', 'Hamburg', 'Germany'),
(208, 'Apple Store Munich', 'Munich', 'Germany'),
(209, 'Apple Store Lyon', 'Lyon', 'France'),
(210, 'Apple Store Nice', 'Nice', 'France'),
(211, 'Apple Store Antwerp', 'Antwerp', 'Belgium'),
(212, 'Apple Store Ghent', 'Ghent', 'Belgium'),
(213, 'Apple Store Lisbon', 'Lisbon', 'Portugal'),
(214, 'Apple Store Porto', 'Porto', 'Portugal'),
(215, 'Apple Store Krakow', 'Krakow', 'Poland'),
(216, 'Apple Store Wroclaw', 'Wroclaw', 'Poland'),
(217, 'Apple Store Brno', 'Brno', 'Czech Republic'),
(218, 'Apple Store Split', 'Split', 'Croatia'),
(219, 'Apple Store Sofia', 'Sofia', 'Bulgaria'),
(220, 'Apple Store Bucharest', 'Bucharest', 'Romania'),
(221, 'Apple Store Tallinn Central', 'Tallinn', 'Estonia'),
(222, 'Apple Store Riga Dome', 'Riga', 'Latvia'),
(223, 'Apple Store Vilnius West', 'Vilnius', 'Lithuania'),
(224, 'Apple Store Havana Centro', 'Havana', 'Cuba'),
(225, 'Apple Store Santo Domingo', 'Santo Domingo', 'Dominican Republic'),
(226, 'Apple Store San Jose', 'San Jose', 'Costa Rica'),
(227, 'Apple Store Guatemala City', 'Guatemala City', 'Guatemala'),
(228, 'Apple Store La Paz', 'La Paz', 'Bolivia'),
(229, 'Apple Store Asuncion', 'Asuncion', 'Paraguay'),
(230, 'Apple Store Montevideo', 'Montevideo', 'Uruguay'),
(231, 'Apple Store Caracas Norte', 'Caracas', 'Venezuela'),
(232, 'Apple Store Medellín', 'Medellín', 'Colombia'),
(233, 'Apple Store Quito', 'Quito', 'Ecuador'),
(234, 'Apple Store Managua', 'Managua', 'Nicaragua'),
(235, 'Apple Store San Salvador', 'San Salvador', 'El Salvador'),
(236, 'Apple Store Tegucigalpa', 'Tegucigalpa', 'Honduras'),
(237, 'Apple Store Port-au-Prince', 'Port-au-Prince', 'Haiti'),
(238, 'Apple Store Kingston West', 'Kingston', 'Jamaica'),
(239, 'Apple Store Accra Central', 'Accra', 'Ghana'),
(240, 'Apple Store Lagos Ikeja', 'Lagos', 'Nigeria'),
(241, 'Apple Store Nairobi CBD', 'Nairobi', 'Kenya'),
(242, 'Apple Store Kigali', 'Kigali', 'Rwanda'),
(243, 'Apple Store Antananarivo', 'Antananarivo', 'Madagascar'),
(244, 'Apple Store Addis Ababa', 'Addis Ababa', 'Ethiopia'),
(245, 'Apple Store Algiers Bay', 'Algiers', 'Algeria'),
(246, 'Apple Store Casablanca Souq', 'Casablanca', 'Morocco'),
(247, 'Apple Store Tunis Medina', 'Tunis', 'Tunisia'),
(248, 'Apple Store Bamako', 'Bamako', 'Mali'),
(249, 'Apple Store Ouagadougou', 'Ouagadougou', 'Burkina Faso'),
(250, 'Apple Store Windhoek West', 'Windhoek', 'Namibia'),
(251, 'Apple Store Dubai Marina', 'Dubai', 'UAE'),
(252, 'Apple Store Abu Dhabi Central', 'Abu Dhabi', 'UAE'),
(253, 'Apple Store Doha Corniche', 'Doha', 'Qatar'),
(254, 'Apple Store Manama Seef', 'Manama', 'Bahrain'),
(255, 'Apple Store Kuwait City Mall', 'Kuwait City', 'Kuwait'),
(256, 'Apple Store Muscat Qurum', 'Muscat', 'Oman'),
(257, 'Apple Store Riyadh Olaya', 'Riyadh', 'Saudi Arabia'),
(258, 'Apple Store Jeddah Red Sea', 'Jeddah', 'Saudi Arabia'),
(259, 'Apple Store Mecca Center', 'Mecca', 'Saudi Arabia'),
(260, 'Apple Store Medina Gate', 'Medina', 'Saudi Arabia'),
(261, 'Apple Store Amman Boulevard', 'Amman', 'Jordan'),
(262, 'Apple Store Beirut Downtown', 'Beirut', 'Lebanon'),
(263, 'Apple Store Damascus City', 'Damascus', 'Syria'),
(264, 'Apple Store Baghdad Green Zone', 'Baghdad', 'Iraq'),
(265, 'Apple Store Erbil Citadel', 'Erbil', 'Iraq'),
(266, 'Apple Store Gaza Central', 'Gaza', 'Palestine'),
(267, 'Apple Store Ramallah Heights', 'Ramallah', 'Palestine'),
(268, 'Apple Store Sana Tower', 'Sana Tower', 'Yemen'),
(269, 'Apple Store Aden Harbor', 'Aden', 'Yemen'),
(270, 'Apple Store Grand Bazaar', 'Tehran', 'Iran'),
(271, 'Apple Store Mashhad Silk Road', 'Mashhad', 'Iran'),
(272, 'Apple Store Shiraz Garden', 'Shiraz', 'Iran'),
(273, 'Apple Store Tabriz Valley', 'Tabriz', 'Iran'),
(274, 'Apple Store Istanbul Bosphorus', 'Istanbul', 'Turkey'),
(275, 'Apple Store Ankara Central', 'Ankara', 'Turkey'),
(276, 'Apple Store Izmir Gulf', 'Izmir', 'Turkey'),
(277, 'Apple Store Aleppo City Mall', 'Aleppo', 'Syria'),
(278, 'Apple Store Homs Junction', 'Homs', 'Syria'),
(279, 'Apple Store Baku Flame Towers', 'Baku', 'Azerbaijan'),
(280, 'Apple Store Dubai Expo', 'Dubai', 'UAE'),
(281, 'Apple Store Sharjah Central', 'Sharjah', 'UAE'),
(282, 'Apple Store Al Ain Oasis', 'Al Ain', 'UAE'),
(283, 'Apple Store Salalah Seaside', 'Salalah', 'Oman'),
(284, 'Apple Store Ras Al Khaimah', 'Ras Al Khaimah', 'UAE'),
(285, 'Apple Store Najaf Central', 'Najaf', 'Iraq'),
(286, 'Apple Store Karbala Horizon', 'Karbala', 'Iraq'),
(287, 'Apple Store Hargeisa City', 'Hargeisa', 'Somaliland'),
(288, 'Apple Store Djibouti Ville', 'Djibouti', 'Djibouti'),
(289, 'Apple Store Khartoum Nile', 'Khartoum', 'Sudan'),
(290, 'Apple Store Tripoli Medina', 'Tripoli', 'Libya'),
(291, 'Apple Store Benghazi East', 'Benghazi', 'Libya'),
(292, 'Apple Store Algiers Casbah', 'Algiers', 'Algeria'),
(293, 'Apple Store Tlemcen Market', 'Tlemcen', 'Algeria'),
(294, 'Apple Store Casablanca Center', 'Casablanca', 'Morocco'),
(295, 'Apple Store Marrakesh Medina', 'Marrakesh', 'Morocco'),
(296, 'Apple Store Rabat Ville', 'Rabat', 'Morocco'),
(297, 'Apple Store Nouakchott West', 'Nouakchott', 'Mauritania'),
(298, 'Apple Store N''Djamena Plaza', 'N''Djamena', 'Chad'),
(299, 'Apple Store Bamako Downtown', 'Bamako', 'Mali'),
(300, 'Apple Store Suva Lagoon', 'Suva', 'Fiji');

INSERT INTO stores (store_id, store_name, city, country)
VALUES
(301, 'Apple Store Port Moresby', 'Port Moresby', 'Papua New Guinea'),
(302, 'Apple Store Wellington Central', 'Wellington', 'New Zealand'),
(303, 'Apple Store Christchurch East', 'Christchurch', 'New Zealand'),
(304, 'Apple Store Auckland North', 'Auckland', 'New Zealand'),
(305, 'Apple Store Hamilton Central', 'Hamilton', 'New Zealand'),
(306, 'Apple Store Dunedin South', 'Dunedin', 'New Zealand'),
(307, 'Apple Store Invercargill West', 'Invercargill', 'New Zealand'),
(308, 'Apple Store Tauranga Bayfair', 'Tauranga', 'New Zealand'),
(309, 'Apple Store Napier Hastings', 'Napier Hastings', 'New Zealand'),
(310, 'Apple Store Rotorua Lakeside', 'Rotorua', 'New Zealand');

INSERT INTO stores (store_id, store_name, city, country)
VALUES
(311, 'Apple Store Honolulu', 'Honolulu', 'USA'),
(312, 'Apple Store Anchorage', 'Anchorage', 'USA'),
(313, 'Apple Store Fairbanks', 'Fairbanks', 'USA'),
(314, 'Apple Store Juneau', 'Juneau', 'USA'),
(315, 'Apple Store Sitka', 'Sitka', 'USA'),
(316, 'Apple Store Ketchikan', 'Ketchikan', 'USA'),
(317, 'Apple Store Kodiak', 'Kodiak', 'USA'),
(318, 'Apple Store Bethel', 'Bethel', 'USA'),
(319, 'Apple Store Nome', 'Nome', 'USA'),
(320, 'Apple Store Barrow', 'Barrow', 'USA');


--🔹 2. Insert Data into category
INSERT INTO category (category_id, category_name)
VALUES
(1, 'Smartphones'),
(2, 'Laptops'),
(3, 'Tablets'),
(4, 'Accessories'),
(5, 'Wearables'),
(6, 'Audio'),
(7, 'Smart Home'),
(8, 'Gaming'),
(9, 'Software'),
(10, 'Services');

select * from stores;
select * from category;